<a href="https://colab.research.google.com/github/himsx/test1/blob/main/13_multi_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Segment 2 - Multiplying matrices and basic linear algebra

In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
np.set_printoptions(precision=2)

## Multiplying matrices and basic linear algebra

In [ ]:
aa = np.array([[2.,4.,6.],[1.,3.,5.],[10.,20.,30.]])
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [ ]:
bb = np.array([[0.,1.,2.],[3.,4.,5.],[6.,7.,8.]])
bb

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
aa*bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [ ]:
np.dot(aa,bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])